version: "3.9"
services:
  frontend:
    container_name: frontendDGB
    build:
      context: ./frontend
      dockerfile: DockerfileFrontendDGB
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Activa polling para asegurar detección de cambios en Docker
    networks:
      - redwebDGB

  backend:
    container_name: backendDGB
    build:
      context: ./backend
      dockerfile: DockerfileBackendDGB
    command: bash -c "composer install && php -S 0.0.0.0:8000 -t public"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - redwebDGB

  web:
    container_name: webDGB
    build:
      context: ./web
      dockerfile: DockerfileWebDGB
    ports:
      - "80:80" # Si tienes problemas con el puerto 80, cambia el puerto externo aquí
    networks:
      - redwebDGB

networks:
  redwebDGB:
    driver: bridge
